# application.yml
---
debug: false

spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:services-config
        prefix: /config

server:
  port: 8001

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8001/eureka

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#    - http://localhost:8001/eureka


#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    service-url:
#      defaultZone: http://localhost:8888/eureka



logging:
  pattern:
    #     console: "%d %-5level %logger : %msg%n"
    #     console: -%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
    console:  -%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr{faint} %clr(%-30.30logger{0}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

  level:
    root: info
    org.springframework.cloud.netflix.zuul: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
    io.voute: DEBUG
