#application.yml

---
spring:
  cloud:
    config:
      fail-fast: true
  data:
    # Atlas: cloud.mongodb.com
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0-x3a8q.mongodb.net/test?retryWrites=true
      database: qe


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

logging:
  pattern:
    console:  -%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr{faint} %clr(%-30.30logger{0}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
  level:
    root: info
    io.demo: debug

---
spring:
  profiles: prod




